export enum DATES_FILED_NOTARY {
  birthDate = 'birthDate',
  passportIssueDate = 'passportIssueDate',
  representativeBirthDate = 'representativeBirthDate',
  date = 'date',
  representativeInternationalPassportIssueDate = 'representativeInternationalPassportIssueDate',
  representativePassportIssueDate = 'representativePassportIssueDate',
  internationalPassportIssueDate = 'internationalPassportIssueDate',
  vehicleRegistrationDate = 'vehicleRegistrationDate',
  parentOneBirthDate = 'parentOneBirthDate',
  passportOneIssueDate = 'passportOneIssueDate',
  parentTwoBirthDate = 'parentTwoBirthDate',
  passportTwoIssueDate = 'passportTwoIssueDate',
  chaperoneBirthDate = 'chaperoneBirthDate',
  minorBirthDate = 'minorBirthDate',
  travelStartDate = 'travelStartDate',
  travelEndDate = 'travelEndDate',
  passportExpiryDate = 'passportExpiryDate',
  marriageCertDate = 'marriageCertDate',
}
