import { DOCUMENT_TYPE } from '@/lib/constants/common-documents';
import { getParentFields, getMinorFields, getChaperoneFields, getTravelDateFields, getMetaFields } from '@/utils/getCommonFormFields';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const commonFormFields: Record<string, any> = {
  ua: {
    person: [
      { name: 'fullName', label: 'ПІБ', type: 'text', required: true },
      { name: 'birthDate', label: 'Дата народження', type: 'date', required: true },
      { name: 'taxId', label: 'ІПН', type: 'text', required: true },
      { name: 'address', label: 'Адреса', type: 'text', required: true },
      {
        name: 'passport',
        label: 'Данні внутрішнього паспорта громадянина (серія та номер, якщо ID - тільки номер)',
        type: 'text',
        required: true,
      },
      { name: 'passportIssueDate', label: 'Дата видачі паспорта', type: 'date', required: true },
      { name: 'passportIssueAuthority', label: 'Ким виданий паспорт', type: 'text', required: true },
    ],
    representative: [
      { name: 'representativeName', label: 'ПІБ представника', type: 'text', required: true },
      { name: 'representativeBirthDate', label: 'Дата народження представника', type: 'date', required: true },
      { name: 'representativeTaxId', label: 'ІПН представника', type: 'text', required: true },
      { name: 'representativeAddress', label: 'Адреса представника', type: 'text', required: true },
    ],
    meta: [
      { name: 'city', label: 'Місто', type: 'text', required: true },
      { name: 'date', label: 'Дата оформлення', type: 'date', required: true },
      { name: 'validUntil', label: 'Термін дії', type: 'radio', required: true, isPeriod: true },
      { name: 'userEmail', label: 'Пошта для відправки згенерованного документа', type: 'email', required: true },
    ],
  },

  en: {
    person: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'birthDate', label: 'Birth Date', type: 'date', required: true },
      { name: 'taxId', label: 'Tax identification number', type: 'text', required: true },
      { name: 'address', label: 'Address', type: 'text', required: true },
      { name: 'passport', label: 'Passport information', type: 'text', required: true },
      { name: 'passportIssueDate', label: 'Passport Issue Date', type: 'date', required: true },
      { name: 'passportIssueAuthority', label: 'Whom give you this passport', type: 'text', required: true },
    ],
    representative: [
      { name: 'representativeName', label: 'Representative Name', type: 'text', required: true },
      { name: 'representativeBirthDate', label: 'Representative Birth Date', type: 'date', required: true },
      { name: 'representativeTaxId', label: 'Representative TIN', type: 'text', required: true },
      { name: 'representativeAddress', label: 'Representative Address', type: 'text', required: true },
    ],
    meta: [
      { name: 'city', label: 'City', type: 'text', required: true },
      { name: 'date', label: 'Date of Document', type: 'date', required: true },
      { name: 'validUntil', label: 'Validity Period', type: 'radio', required: true, isPeriod: true },
      { name: 'userEmail', label: 'Email for send generated document', type: 'email', required: true },
    ],
  },
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const formFieldsSchemas: Record<string, Record<string, any>> = {
  [DOCUMENT_TYPE.PAWER_OF_ATTORNEY_PROPERTY]: {
    ua: {
      ...commonFormFields.ua,
      property: [
        { name: 'propertyAddress.city', label: 'Місто нерухомості', type: 'text', required: false },
        { name: 'propertyAddress.street', label: 'Вулиця', type: 'text', required: false },
        {
          name: 'propertyAddress.propertyType',
          label: 'Тип нерухомості',
          type: 'select',
          required: true,
          options: [
            { value: 'house', label: 'Житловий будинок' },
            { value: 'apartment', label: 'Квартира' },
            { value: 'nonResidential', label: 'Нежитлове приміщення' },
          ],
        },
        { name: 'propertyAddress.buildNumber', label: 'Номер будинку', type: 'text', required: false },
        {
          name: 'propertyAddress.apartment',
          label: '№ квартири/приміщення',
          type: 'text',
          required: false,
          watchingField: 'propertyAddress.propertyType',
          watchingValue: 'apartment',
        },
        { name: 'propertyAddress.postCode', label: 'Поштовий індекс', type: 'text', required: false },
      ],
    },
    en: {
      ...commonFormFields.en,
      property: [
        { name: 'propertyAddress.city', label: 'City of property', type: 'text', required: false },
        { name: 'propertyAddress.street', label: 'Street', type: 'text', required: false },
        {
          name: 'propertyAddress.propertyType',
          label: 'Property Type',
          type: 'select',
          required: true,
          options: [
            { value: 'house', label: 'Residential House' },
            { value: 'apartment', label: 'Apartment' },
            { value: 'nonResidential', label: 'Non-Residential Premises' },
          ],
        },
        { name: 'propertyAddress.buildNumber', label: 'Number of Building', type: 'text', required: false },
        {
          name: 'propertyAddress.apartment',
          label: '№ apartment/non-residental',
          type: 'text',
          required: false,
          watchingField: 'propertyAddress.propertyType',
          watchingValue: 'apartment',
        },
        { name: 'propertyAddress.postCode', label: 'Post Code', type: 'text', required: false },
      ],
    },
  },
  [DOCUMENT_TYPE.powerOfAttorneyDocuments]: {
    ...commonFormFields,
  },
  [DOCUMENT_TYPE.powerAttorneyVehicle]: {
    ua: {
      person: [
        { name: 'fullName', label: 'ПІБ', type: 'text', required: true },
        { name: 'birthDate', label: 'Дата народження', type: 'date', required: true },
        { name: 'taxId', label: 'ІПН', type: 'text', required: true },
        {
          name: 'passport',
          label: 'Данні внутрішнього паспорта громадянина (серія та номер, якщо ID - тільки номер)',
          type: 'text',
          required: true,
        },
        { name: 'passportIssueDate', label: 'Дата видачі внутрішнього паспорта громадянина', type: 'date', required: true },
        {
          name: 'passportIssueAuthority',
          label: 'Ким виданий внутрішній паспорт громадянина (якщо ID, номер органу)',
          type: 'text',
          required: true,
        },
        { name: 'internationalPassport', label: 'Серія та номер паспорта для виїзду за кордон', type: 'text', required: true },
        { name: 'internationalPassportIssueDate', label: 'Дата видачі паспорта для виїзду за кордон', type: 'date', required: true },
        {
          name: 'internationalPassportIssueAuthority',
          label: 'Орган, що видав паспорт для виїзду за кордон',
          type: 'text',
          required: true,
        },
      ],
      representative: [
        { name: 'representativeName', label: 'ПІБ представника', type: 'text', required: true },
        { name: 'representativeBirthDate', label: 'Дата народження', type: 'date', required: true },
        { name: 'representativeTaxId', label: 'ІПН представника', type: 'text', required: true },
        { name: 'representativePassport', label: 'Данні внутрішнього паспорта громадянина', type: 'text', required: true },
        { name: 'representativePassportIssueDate', label: 'Дата видачі внутрішнього паспорта громадянина', type: 'date', required: true },
        {
          name: 'representativePassportIssueAuthority',
          label: 'Ким виданий внутрішній паспорт громадянина',
          type: 'text',
          required: true,
        },
        { name: 'representativeInternationalPassportSeries', label: 'Серія паспорта для виїзду за кордон', type: 'text', required: true },
        { name: 'representativeInternationalPassportNumber', label: 'Номер паспорта для виїзду за кордон', type: 'text', required: true },
        {
          name: 'representativeInternationalPassportIssueDate',
          label: 'Дата видачі паспорта для виїзду за кордон',
          type: 'date',
          required: true,
        },
        {
          name: 'representativeInternationalPassportAuthority',
          label: 'Орган, що видав паспорта для виїзду за кордон',
          type: 'text',
          required: true,
        },
      ],
      vehicle: [
        { name: 'car.vehicleMake', label: 'Марка', type: 'text', required: true },
        { name: 'car.vehicleModel', label: 'Модель', type: 'text', required: true },
        { name: 'car.vehicleYear', label: 'Рік випуску', type: 'text', required: true },
        { name: 'car.vehicleColor', label: 'Колір', type: 'text', required: true },
        { name: 'car.vehicleVin', label: 'Номер шасі (VIN)', type: 'text', required: true },
        { name: 'car.vehicleLicensePlate', label: 'Реєстраційний номер', type: 'text', required: true },
        { name: 'car.vehicleType', label: 'Тип ТЗ', type: 'text', required: true },
        { name: 'car.vehicleRegistrationCertificate', label: 'Номер свідоцтва про реєстрацію', type: 'text', required: true },
        { name: 'car.vehicleRegistrationAuthority', label: 'Ким видано свідоцтво', type: 'text', required: true },
        { name: 'car.vehicleRegistrationDate', label: 'Дата реєстрації', type: 'date', required: true },
      ],
      meta: [
        { name: 'city', label: 'Місто складання довіреності', type: 'text', required: true },
        { name: 'date', label: 'Дата складання', type: 'date', required: true },
        { name: 'validUntil', label: 'Термін дії', type: 'radio', required: true, isPeriod: true },
        { name: 'userEmail', label: 'Ваша пошта для отримання документа', type: 'email', required: true },
      ],
    },
    en: {
      person: [
        { name: 'fullName', label: 'Full Name', type: 'text', required: true },
        { name: 'birthDate', label: 'Date of Birth', type: 'date', required: true },
        { name: 'taxId', label: 'Tax ID', type: 'text', required: true },
        {
          name: 'passport',
          label: 'Passport information',
          type: 'text',
          required: true,
        },
        { name: 'passportIssueDate', label: 'Date of Issue', type: 'date', required: true },
        { name: 'passportIssueAuthority', label: 'Issuing Authority', type: 'text', required: true },
        { name: 'internationalPassport', label: 'International passport information', type: 'text', required: true },
        { name: 'internationalPassportIssueDate', label: 'Date of Issue', type: 'date', required: true },
        { name: 'internationalPassportIssueAuthority', label: 'Issuing Authority', type: 'text', required: true },
      ],
      representative: [
        { name: 'representativeName', label: "Representative's Full Name", type: 'text', required: true },
        { name: 'representativeBirthDate', label: 'Date of Birth', type: 'date', required: true },
        { name: 'representativeTaxId', label: "Representative's Tax ID", type: 'text', required: true },
        { name: 'representativePassportSeries', label: 'Passport Series', type: 'text', required: true },
        { name: 'representativePassportNumber', label: 'Passport Number', type: 'text', required: true },
        { name: 'representativePassportIssueDate', label: 'Date of Issue', type: 'date', required: true },
        { name: 'representativePassportIssueAuthority', label: 'Issuing Authority', type: 'text', required: true },
        { group: "Representative's International Passport" },
        { name: 'representativeInternationalPassportSeries', label: 'Series', type: 'text', required: true },
        { name: 'representativeInternationalPassportNumber', label: 'Number', type: 'text', required: true },
        { name: 'representativeInternationalPassportIssueDate', label: 'Date of Issue', type: 'date', required: true },
        { name: 'representativeInternationalPassportAuthority', label: 'Issuing Authority', type: 'text', required: true },
      ],
      vehicle: [
        { name: 'car.vehicleMake', label: 'Make', type: 'text', required: true },
        { name: 'car.vehicleModel', label: 'Model', type: 'text', required: true },
        { name: 'car.vehicleYear', label: 'Year of Manufacture', type: 'number', required: true },
        { name: 'car.vehicleColor', label: 'Color', type: 'text', required: true },
        { name: 'car.vehicleVin', label: 'Chassis Number (VIN)', type: 'text', required: true },
        { name: 'car.vehicleLicensePlate', label: 'Registration Number', type: 'text', required: true },
        { name: 'car.vehicleType', label: 'Vehicle Type', type: 'text', required: true },
        { name: 'car.vehicleRegistrationCertificate', label: 'Registration Certificate No.', type: 'text', required: true },
        { name: 'car.vehicleRegistrationAuthority', label: 'Certificate Issuing Authority', type: 'text', required: true },
        { name: 'car.vehicleRegistrationDate', label: 'Date of Registration', type: 'date', required: true },
      ],
      meta: [
        { name: 'city', label: 'City of Signing', type: 'text', required: true },
        { name: 'date', label: 'Date of Signing', type: 'date', required: true },
        { name: 'validUntil', label: 'Validity Period', type: 'radio', required: true, isPeriod: true },
        { name: 'userEmail', label: 'Your Email to Receive the Document', type: 'email', required: true },
      ],
    },
  },
  [DOCUMENT_TYPE.consentForMinorToTravelAboard]: {
    ua: {
      person: [...getParentFields('ua')],
      representative: [...getChaperoneFields('ua', 'chaperone')],
      minor: [...getMinorFields('ua'), ...getTravelDateFields('ua')],
      meta: [...getMetaFields('ua')],
    },
    en: {
      person: [...getParentFields('en')],
      representative: [...getChaperoneFields('ua', 'chaperone')],
      minor: [...getMinorFields('en'), ...getTravelDateFields('en')],
      meta: [...getMetaFields('en')],
    },
  },
  [DOCUMENT_TYPE.consentToSellProperty]: {
    ua: {
      person: [
        { name: 'fullName', label: 'ПІБ особи, яка надає згоду', type: 'text', required: true },
        { name: 'birthDate', label: 'Дата народження', type: 'date', required: true },
        { name: 'taxId', label: 'ІПН (Реєстраційний номер облікової картки платника податків)', type: 'text', required: true },
        { name: 'address', label: 'Адреса зареєстрованого місця проживання', type: 'text', required: true },
        { name: 'passportCountryCode', label: 'Код країни (напр. UKR)', type: 'text', required: true },
        { name: 'passportInternation', label: 'Номер та серія закордонного паспорта', type: 'text', required: true },
        { name: 'passportIssueDate', label: 'Дата видачі паспорта', type: 'date', required: true },
        { name: 'passportIssuingAuthority', label: 'Орган, що видав паспорт (4 цифри)', type: 'text', required: true },
        { name: 'passportExpiryDate', label: 'Дата закінчення терміну дії', type: 'date', required: true },
      ],
      representative: [
        { name: 'spouseFullName', label: 'ПІБ чоловіка/дружини (кому надається згода)', type: 'text', required: true },
        { name: 'marriageCertNumber', label: 'Номер свідоцтва про шлюб', type: 'text', required: true },
        { name: 'marriageCertIssuer', label: 'Орган, що видав свідоцтво', type: 'text', required: true },
        { name: 'marriageCertDate', label: 'Дата видачі свідоцтва', type: 'date', required: true },
        { name: 'marriageCertRecordNumber', label: 'Номер актового запису', type: 'text', required: true },
      ],
      property: [
        {
          name: 'propertyType',
          label: 'Тип нерухомості',
          type: 'select',
          required: true,
          options: [
            { value: 'house', label: 'Житловий будинок' },
            { value: 'apartment', label: 'Квартира' },
            { value: 'nonResidential', label: 'Нежитлове приміщення' },
          ],
        },
        { name: 'propertyArea', label: 'Загальна площа (кв.м.)', type: 'text', required: true },
        { name: 'propertyAddressForSell', label: 'Адреса нерухомості', type: 'text', required: true },
        {
          name: 'includeLand',
          label: 'Інформація про земельну ділянку',
          singleCheckboxLabel: 'Продаж також включає земельну ділянку',
          type: 'checkbox',
          isWatchingCheckbox: true,
          watchingField: 'propertyType',
          watchingValue: 'house',
        },
        { name: 'landArea', label: 'Площа земельної ділянки (га)', type: 'text', required: true, conditionalOn: 'includeLand' },
        { name: 'landCadastralNumber', label: 'Кадастровий номер ділянки', type: 'text', required: true, conditionalOn: 'includeLand' },
      ],
      meta: [
        { name: 'date', label: 'Дата підписання документа', type: 'date', required: true },
        { name: 'userEmail', label: 'Email для отримання готового документа', type: 'email', required: true },
      ],
    },
    en: {
      person: [
        { name: 'fullName', label: "Grantor's Full Name", type: 'text', required: true },
        { name: 'birthDate', label: 'Date of Birth', type: 'date', required: true },
        { name: 'taxId', label: 'TIN (Taxpayer Identification Number)', type: 'text', required: true },
        { name: 'address', label: 'Registered Place of Residence Address', type: 'text', required: true },
        { name: 'passportCountryCode', label: 'Country Code (e.g., UKR)', type: 'text', required: true },
        { name: 'passportInternation', label: 'Passport Number and series', type: 'text', required: true },
        { name: 'passportIssueDate', label: 'Date of Issue', type: 'date', required: true },
        { name: 'passportIssuingAuthority', label: 'Issuing Authority (4 digits)', type: 'text', required: true },
        { name: 'passportExpiryDate', label: 'Date of Expiry', type: 'date', required: true },
      ],
      representative: [
        { name: 'spouseFullName', label: 'Full Name of Spouse (to whom consent is granted)', type: 'text', required: true },
        { name: 'marriageCertNumber', label: 'Marriage Certificate Number', type: 'text', required: true },
        { name: 'marriageCertIssuer', label: 'Issuing Authority of Certificate', type: 'text', required: true },
        { name: 'marriageCertDate', label: 'Date of Certificate Issue', type: 'date', required: true },
        { name: 'marriageCertRecordNumber', label: 'Act Record Number', type: 'text', required: true },
      ],
      property: [
        {
          name: 'propertyType',
          label: 'Property Type',
          type: 'select',
          required: true,
          options: [
            { value: 'house', label: 'Residential House' },
            { value: 'apartment', label: 'Apartment' },
            { value: 'nonResidential', label: 'Non-Residential Premises' },
          ],
        },
        { name: 'propertyArea', label: 'Total Area (sq.m.)', type: 'text', required: true },
        { name: 'propertyAddressForSell', label: 'Property Address', type: 'text', required: true },
        {
          name: 'includeLand',
          label: 'Information about land',
          singleCheckboxLabel: 'The sale also includes the land plot',
          type: 'checkbox',
          isWatchingCheckbox: true,
          watchingField: 'propertyType',
          watchingValue: 'house',
        },
        { name: 'landArea', label: 'Land Plot Area (ha)', type: 'text', required: true, conditionalOn: 'includeLand' },
        { name: 'landCadastralNumber', label: 'Cadastral Number of the Plot', type: 'text', required: true, conditionalOn: 'includeLand' },
      ],
      meta: [
        { name: 'date', label: 'Date of Signing', type: 'date', required: true },
        { name: 'userEmail', label: 'Email to Receive the Final Document', type: 'email', required: true },
      ],
    },
  },
};
